import type { Hono } from 'hono';

// Generated by `npx wrangler types` — extends worker-configuration.d.ts
// We define the shape manually for type safety without running wrangler types

export interface AppEnv {
  Bindings: {
    DB: D1Database;
    KV: KVNamespace;
    HACKATHON_SM: DurableObjectNamespace;
    WEBHOOK_QUEUE: Queue;
    NOTIFICATION_QUEUE: Queue;
    // UPLOADS: R2Bucket; // disabled until R2 is enabled
    // Secrets
    JWT_SECRET: string;
    GITHUB_WEBHOOK_SECRET: string;
    SMTP_URL: string;
    SMTP_USERNAME: string;
    SMTP_PASSWORD: string;
    SMTP_EMAIL_ADDR?: string;
    GEMINI_API_KEY?: string;
    GITHUB_CLIENT_ID?: string;
    GITHUB_CLIENT_SECRET?: string;
    // Vars
    NODE_ENV?: string;
    FRONTEND_URL: string;
    PLATFORM_URL: string;
    ADMIN_URL: string;
    API_URL: string;
    EMAIL_FROM: string;
    HACKATHON_ORIGIN_PATTERN?: string;
    PAGES_ORIGIN_PATTERN?: string;
  };
  Variables: {
    user: UserContext | null;
    requestId: string;
    hackathon?: HackathonContext;
    role?: HackathonRole;
  };
}

export interface UserContext {
  id: string;
  email: string;
  name: string;
  avatar_url: string | null;
  github_username: string;
  created_at: string;
}

export interface HackathonContext {
  id: string;
  workspace_id: string;
  slug: string;
  status: string;
}

export type HackathonRole = 'organizer' | 'co_organizer' | 'judge' | 'leader' | 'member' | 'anonymous';
