import type { Hono } from 'hono';

// Generated by `npx wrangler types` — extends worker-configuration.d.ts
// We define the shape manually for type safety without running wrangler types

export interface AppEnv {
  Bindings: {
    DB: D1Database;
    KV: KVNamespace;
    HACKATHON_SM: DurableObjectNamespace;
    WEBHOOK_QUEUE: Queue;
    NOTIFICATION_QUEUE: Queue;
    // UPLOADS: R2Bucket; // disabled until R2 is enabled
    // Secrets
    JWT_SECRET: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    // Vars
    FRONTEND_URL: string;
    PLATFORM_URL: string;
    ADMIN_URL: string;
    API_URL: string;
    EMAIL_FROM: string;
  };
  Variables: {
    user: UserContext | null;
    requestId: string;
    hackathon?: HackathonContext;
    role?: HackathonRole;
  };
}

export interface UserContext {
  id: string;
  email: string;
  name: string;
  github_id: number | null;
  github_username: string | null;
  avatar_url: string | null;
}

export interface HackathonContext {
  id: string;
  workspace_id: string;
  slug: string;
  status: string;
}

export type HackathonRole = 'organizer' | 'co_organizer' | 'judge' | 'team_lead' | 'team_member' | 'anonymous';
